import { useMemo, useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import { Drawer } from '../components/Drawer';
import { StatCard, StatusTag } from '../components/Ledger';
import { useRecruitment, type Candidate } from '../data/recruitment';
import { CATEGORIES, useOnboarding, type BankDetails, type EmergencyContact, type OnboardingCategory, type OnboardingDocumentType, type OnboardingRecord, type PersonalInformation } from '../data/onboarding';
import { useEmployees } from '../data/employees';
import { useDepartments } from '../data/departments';
import { useDesignations } from '../data/designations';
import type { Role } from '../data/roles';

const STATUS_LABEL = { PENDING: 'Pending', IN_PROGRESS: 'In progress', COMPLETED: 'Completed' } as const;
const STATUS_KIND = { PENDING: 'neutral', IN_PROGRESS: 'pending', COMPLETED: 'present' } as const;
const inputStyle = { borderColor: 'var(--line)', borderRadius: 'var(--radius-sm)' } as const;
type Ctx = { role: Role };
type TaskMode = 'personal' | 'emergency' | 'identity' | 'offer' | 'bank' | null;

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="text-xs font-medium uppercase tracking-wide" style={{ color: 'var(--text-secondary)' }}>{label}</span><div className="mt-1.5">{children}</div></label>; }
function weekRange() { const today = new Date(); const start = new Date(today); start.setDate(today.getDate() - today.getDay() + 1); const end = new Date(start); end.setDate(start.getDate() + 6); return [start.toISOString().slice(0, 10), end.toISOString().slice(0, 10)]; }
function emptyPersonal(record: OnboardingRecord): PersonalInformation { return { full_name: record.personal?.full_name ?? record.candidate.name, date_of_birth: record.personal?.date_of_birth ?? '', gender: record.personal?.gender ?? '', personal_email: record.personal?.personal_email ?? record.candidate.email, phone: record.personal?.phone ?? record.candidate.phone, alternate_phone: record.personal?.alternate_phone ?? '', address: record.personal?.address ?? '', city: record.personal?.city ?? '', state: record.personal?.state ?? '', postal_code: record.personal?.postal_code ?? '', country: record.personal?.country ?? '' }; }

export default function OnboardingPage() {
    const { role } = useOutletContext<Ctx>();
    const { candidates, updateCandidate } = useRecruitment();
    const { addEmployee } = useEmployees();
    const { departments } = useDepartments();
    const { designations } = useDesignations();
    const onboarding = useOnboarding(candidates);
    const { records, startOnboarding, activateEmployee, savePersonal, saveEmergency, saveBank, uploadDocument, viewDocument, loading, actionLoading, error } = onboarding;
    const [selectedId, setSelectedId] = useState<string | null>(null);
    const [joinerCandidateId, setJoinerCandidateId] = useState('');
    const [joiningDate, setJoiningDate] = useState('');
    const [search, setSearch] = useState('');
    const [taskMode, setTaskMode] = useState<TaskMode>(null);
    const [message, setMessage] = useState<string | null>(null);
    const [personal, setPersonal] = useState<PersonalInformation | null>(null);
    const [emergency, setEmergency] = useState<EmergencyContact>({ contact_name: '', relationship: '', phone: '', alternate_phone: '', address: '' });
    const [bank, setBank] = useState<BankDetails>({ account_holder_name: '', bank_name: '', account_number: '', ifsc_code: '', branch: '' });
    const [drawerError, setDrawerError] = useState<string | null>(null);

    const [weekStart, weekEnd] = weekRange();
    const selected = selectedId ? records.find((record) => record.id === selectedId) ?? null : null;
    const stats = useMemo(() => ({ pending: records.filter((record) => record.status === 'PENDING').length, progress: records.filter((record) => record.status === 'IN_PROGRESS').length, completed: records.filter((record) => record.status === 'COMPLETED').length, joining: records.filter((record) => record.joining_date >= weekStart && record.joining_date <= weekEnd).length }), [records, weekStart, weekEnd]);
    const candidatesWithoutOnboarding = candidates.filter((candidate) => ['SELECTED', 'OFFER_SENT', 'HIRED'].includes(candidate.stage) && !records.some((record) => record.candidate_id === candidate.id));
    const filtered = records.filter((record) => `${record.candidate.name} ${record.candidate.email}`.toLowerCase().includes(search.toLowerCase()));

    function openRecord(record: OnboardingRecord) { setSelectedId(record.id); setTaskMode(null); setDrawerError(null); setMessage(null); setPersonal(emptyPersonal(record)); setEmergency(record.emergency ?? { contact_name: '', relationship: '', phone: '', alternate_phone: '', address: '' }); setBank(record.bank ?? { account_holder_name: record.candidate.name, bank_name: '', account_number: '', ifsc_code: '', branch: '' }); }
    async function createJoiner(event: React.FormEvent) { event.preventDefault(); const candidate = candidates.find((item) => item.id === joinerCandidateId); if (!candidate || !joiningDate) return; if (await startOnboarding(candidate, joiningDate)) { setJoinerCandidateId(''); setJoiningDate(''); setSelectedId(null); setMessage('Onboarding started successfully.'); } }
    async function activate(record: OnboardingRecord) { const candidate = record.candidate; const department = departments.find((item) => item.name.toLowerCase().includes('engineering')) ?? departments[0]; const designation = designations.find((item) => item.department_id === department?.id); if (!department || !designation) return; const employeeId = await addEmployee({ name: candidate.name, email: candidate.email, phone: candidate.phone, department_id: department.id, designation_id: designation.id, manager_id: null, joining_date: record.joining_date, employment_status: 'ACTIVE', work_mode: 'OFFICE' }); if (employeeId && await activateEmployee(record.id, employeeId)) { await updateCandidate(record.candidate_id, { stage: 'HIRED' }); setMessage('Employee activated successfully.'); } }
    async function savePersonalInfo(event: React.FormEvent) { event.preventDefault(); if (!selected || !personal) return; if (await savePersonal(selected, personal)) { setMessage('Personal information saved.'); setTaskMode(null); } }
    async function saveEmergencyInfo(event: React.FormEvent) { event.preventDefault(); if (!selected) return; if (await saveEmergency(selected, emergency)) { setMessage('Emergency contact saved.'); setTaskMode(null); } }
    async function saveBankInfo(event: React.FormEvent) { event.preventDefault(); if (!selected) return; if (await saveBank(selected, bank)) { setMessage('Bank details saved.'); setTaskMode(null); } }
    async function handleUpload(type: OnboardingDocumentType, file: File | undefined) { if (!selected || !file) return; if (await uploadDocument(selected, type, file)) { setMessage(`${type.replace('_', ' ')} uploaded successfully.`); } }
    async function view(documentPath: any) { const url = await viewDocument(documentPath); if (url) window.open(url, '_blank', 'noopener,noreferrer'); }
    function activateTask(record: OnboardingRecord, task: OnboardingRecord['tasks'][number]) { if (task.completed) return; setDrawerError(null); if (task.label === 'Collect personal details') { setPersonal(emptyPersonal(record)); setTaskMode('personal'); } else if (task.label === 'Confirm emergency contact') { setEmergency(record.emergency ?? { contact_name: '', relationship: '', phone: '', alternate_phone: '', address: '' }); setTaskMode('emergency'); } else if (task.label === 'Verify identity documents') setTaskMode('identity'); else if (task.label === 'Collect signed offer letter') setTaskMode('offer'); else if (task.label === 'Collect bank details') { setBank(record.bank ?? { account_holder_name: record.candidate.name, bank_name: '', account_number: '', ifsc_code: '', branch: '' }); setTaskMode('bank'); } }

    if (role !== 'HR' && role !== 'SUPER_ADMIN') return <div className="border bg-white p-8 text-center" style={{ borderColor: 'var(--line-soft)', borderRadius: 'var(--radius-md)' }}>Onboarding is available to HR only.</div>;
    if (loading) return <p className="py-12 text-center font-mono text-xs uppercase tracking-wide" style={{ color: 'var(--text-muted)' }}>Loading onboarding information...</p>;

    return <div className="space-y-6">
        {(error || drawerError) && <div className="border border-red-300 bg-red-50 px-4 py-3 text-sm text-red-800">{drawerError ?? error}</div>}
        {message && <div className="border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">{message}</div>}
        <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[0.16em]" style={{ color: 'var(--status-present)' }}>People operations</p><h1 className="font-display mt-1 text-2xl font-semibold" style={{ color: 'var(--ink)' }}>Onboarding</h1><p className="mt-1 text-sm" style={{ color: 'var(--text-secondary)' }}>Guide new joiners from offer acceptance to their first day.</p></div><div className="flex gap-2"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search joiners" className="border bg-white px-3 py-2 text-sm" style={inputStyle} /><button onClick={() => setJoinerCandidateId(candidatesWithoutOnboarding[0]?.id ?? '')} className="px-4 py-2.5 text-sm font-medium" style={{ background: 'var(--ink)', color: '#fff', borderRadius: 'var(--radius-sm)' }}>+ Start onboarding</button></div></div>
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Pending" value={stats.pending} status="neutral" /><StatCard label="In progress" value={stats.progress} status="pending" /><StatCard label="Completed" value={stats.completed} status="present" /><StatCard label="Joining this week" value={stats.joining} status="structure" /></div>
        <div className="border bg-white" style={{ borderColor: 'var(--line-soft)', borderRadius: 'var(--radius-md)' }}><div className="border-b px-5 py-3.5" style={{ borderColor: 'var(--line-soft)' }}><h2 className="text-sm font-semibold" style={{ color: 'var(--ink)' }}>New joiners</h2></div><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left"><thead style={{ background: 'var(--paper)' }}><tr>{['Employee', 'Joining date', 'Department', 'Progress', 'Status'].map((heading) => <th key={heading} className="px-5 py-3 font-mono text-[10px] uppercase tracking-wide" style={{ color: 'var(--text-secondary)' }}>{heading}</th>)}</tr></thead><tbody>{filtered.length === 0 ? <tr><td colSpan={5} className="px-5 py-10 text-center text-sm" style={{ color: 'var(--text-muted)' }}>No onboarding records found.</td></tr> : filtered.map((record) => <tr key={record.id} onClick={() => openRecord(record)} className="cursor-pointer border-t transition-colors hover:bg-[var(--paper)]" style={{ borderColor: 'var(--line-soft)' }}><td className="px-5 py-3 text-sm font-medium" style={{ color: 'var(--ink)' }}>{record.candidate.name}</td><td className="px-5 py-3 text-sm" style={{ color: 'var(--text-secondary)' }}>{record.joining_date}</td><td className="px-5 py-3 text-sm" style={{ color: 'var(--text-secondary)' }}>Employee onboarding</td><td className="px-5 py-3"><div className="flex items-center gap-3"><div className="h-2 w-28 overflow-hidden bg-[var(--paper)]"><div className="h-full" style={{ width: `${record.progress}%`, background: 'var(--accent-structure)' }} /></div><span className="font-mono text-xs">{record.progress}%</span></div></td><td className="px-5 py-3"><StatusTag label={STATUS_LABEL[record.status]} status={STATUS_KIND[record.status]} /></td></tr>)}</tbody></table></div></div>

        <Drawer open={!!selected} title={selected ? `${selected.candidate.name} onboarding` : 'Onboarding profile'} onClose={() => setSelectedId(null)}>{selected && <div className="space-y-5"><div className="border-b pb-4" style={{ borderColor: 'var(--line-soft)' }}><p className="text-lg font-semibold" style={{ color: 'var(--ink)' }}>{selected.candidate.name}</p><p className="mt-1 text-sm" style={{ color: 'var(--text-secondary)' }}>{selected.candidate.email} · {selected.candidate.phone || 'No phone'}</p><p className="mt-2 font-mono text-xs uppercase" style={{ color: 'var(--text-secondary)' }}>Joining {selected.joining_date}</p></div>{!selected.started && <button onClick={() => { void startOnboarding(selected.candidate, selected.joining_date); }} className="w-full py-2.5 text-sm font-medium" style={{ background: 'var(--ink)', color: '#fff', borderRadius: 'var(--radius-sm)' }}>Start onboarding</button>}<div><div className="flex items-center justify-between"><p className="font-mono text-[10px] uppercase tracking-wide" style={{ color: 'var(--text-secondary)' }}>Checklist completion</p><span className="font-mono text-sm font-semibold" style={{ color: 'var(--accent-structure)' }}>{selected.progress}%</span></div><div className="mt-2 h-2 overflow-hidden bg-[var(--paper)]"><div className="h-full" style={{ width: `${selected.progress}%`, background: 'var(--accent-structure)' }} /></div></div>{CATEGORIES.map((category: OnboardingCategory) => <section key={category}><h3 className="border-b pb-2 text-xs font-semibold uppercase tracking-wide" style={{ color: 'var(--ink)', borderColor: 'var(--line-soft)' }}>{category}</h3><div className="mt-2 space-y-1">{selected.tasks.filter((task) => task.category === category).map((task) => <button type="button" key={task.id} onClick={() => activateTask(selected, task)} className="flex w-full items-center gap-3 px-2 py-2 text-left text-sm hover:bg-[var(--paper)]" style={{ color: task.completed ? 'var(--text-secondary)' : 'var(--ink)' }}><input type="checkbox" readOnly checked={task.completed} /><span className={task.completed ? 'line-through' : ''}>{task.label}</span></button>)}</div></section>)}{selected.employee_id && selected.status !== 'COMPLETED' && <button onClick={() => { void activate(selected); }} className="w-full border px-3 py-2 text-sm font-medium" style={{ borderColor: 'var(--line)', color: 'var(--ink)', borderRadius: 'var(--radius-sm)' }}>Activate employee</button>}{taskMode && <div className="border-t pt-4" style={{ borderColor: 'var(--line-soft)' }}>
            {taskMode === 'personal' && personal && <form onSubmit={savePersonalInfo} className="space-y-3"><h3 className="text-sm font-semibold" style={{ color: 'var(--ink)' }}>Personal information</h3><div className="grid grid-cols-2 gap-3"><Field label="Full name"><input required value={personal.full_name} onChange={(event) => setPersonal({ ...personal, full_name: event.target.value })} className="w-full border px-2.5 py-2 text-sm" style={inputStyle} /></Field><Field label="Date of birth"><input type="date" value={personal.date_of_birth} onChange={(event) => setPersonal({ ...personal, date_of_birth: event.target.value })} className="w-full border px-2.5 py-2 text-sm" style={inputStyle} /></Field><Field label="Gender"><input value={personal.gender} onChange={(event) => setPersonal({ ...personal, gender: event.target.value })} className="w-full border px-2.5 py-2 text-sm" style={inputStyle} /></Field><Field label="Personal email"><input type="email" value={personal.personal_email} onChange={(event) => setPersonal({ ...personal, personal_email: event.target.value })} className="w-full border px-2.5 py-2 text-sm" style={inputStyle} /></Field><Field label="Phone"><input required value={personal.phone} onChange={(event) => setPersonal({ ...personal, phone: event.target.value })} className="w-full border px-2.5 py-2 text-sm" style={inputStyle} /></Field><Field label="Alternate phone"><input value={personal.alternate_phone} onChange={(event) => setPersonal({ ...personal, alternate_phone: event.target.value })} className="w-full border px-2.5 py-2 text-sm" style={inputStyle} /></Field></div><Field label="Address"><textarea value={personal.address} onChange={(event) => setPersonal({ ...personal, address: event.target.value })} rows={2} className="w-full resize-none border px-2.5 py-2 text-sm" style={inputStyle} /></Field><div className="grid grid-cols-2 gap-3"><Field label="City"><input value={personal.city} onChange={(event) => setPersonal({ ...personal, city: event.target.value })} className="w-full border px-2.5 py-2 text-sm" style={inputStyle} /></Field><Field label="State"><input value={personal.state} onChange={(event) => setPersonal({ ...personal, state: event.target.value })} className="w-full border px-2.5 py-2 text-sm" style={inputStyle} /></Field><Field label="Postal code"><input value={personal.postal_code} onChange={(event) => setPersonal({ ...personal, postal_code: event.target.value })} className="w-full border px-2.5 py-2 text-sm" style={inputStyle} /></Field><Field label="Country"><input value={personal.country} onChange={(event) => setPersonal({ ...personal, country: event.target.value })} className="w-full border px-2.5 py-2 text-sm" style={inputStyle} /></Field></div><button disabled={actionLoading} className="w-full py-2 text-sm font-medium disabled:opacity-60" style={{ background: 'var(--ink)', color: '#fff', borderRadius: 'var(--radius-sm)' }}>Save Personal Information</button></form>}
            {taskMode === 'emergency' && <form onSubmit={saveEmergencyInfo} className="space-y-3"><h3 className="text-sm font-semibold" style={{ color: 'var(--ink)' }}>Emergency contact</h3>{(['contact_name', 'relationship', 'phone', 'alternate_phone', 'address'] as const).map((field) => <Field key={field} label={field.replace('_', ' ')}><input required={field === 'contact_name' || field === 'relationship' || field === 'phone'} value={emergency[field]} onChange={(event) => setEmergency({ ...emergency, [field]: event.target.value })} className="w-full border px-2.5 py-2 text-sm" style={inputStyle} /></Field>)}<button disabled={actionLoading} className="w-full py-2 text-sm font-medium disabled:opacity-60" style={{ background: 'var(--ink)', color: '#fff', borderRadius: 'var(--radius-sm)' }}>Save Emergency Contact</button></form>}
            {taskMode === 'bank' && <form onSubmit={saveBankInfo} className="space-y-3"><h3 className="text-sm font-semibold" style={{ color: 'var(--ink)' }}>Bank details</h3>{(['account_holder_name', 'bank_name', 'account_number', 'ifsc_code', 'branch'] as const).map((field) => <Field key={field} label={field.replaceAll('_', ' ')}><input required={field !== 'branch'} type={field === 'account_number' ? 'password' : 'text'} value={bank[field]} onChange={(event) => setBank({ ...bank, [field]: event.target.value })} className="w-full border px-2.5 py-2 text-sm" style={inputStyle} /></Field>)}<button disabled={actionLoading} className="w-full py-2 text-sm font-medium disabled:opacity-60" style={{ background: 'var(--ink)', color: '#fff', borderRadius: 'var(--radius-sm)' }}>Save Bank Details</button></form>}
            {(taskMode === 'identity' || taskMode === 'offer') && <div className="space-y-3"><h3 className="text-sm font-semibold" style={{ color: 'var(--ink)' }}>{taskMode === 'identity' ? 'Identity documents' : 'Signed offer letter'}</h3>{(taskMode === 'identity' ? [{ type: 'AADHAAR' as const, label: 'Aadhaar Card' }, { type: 'PAN' as const, label: 'PAN Card' }] : [{ type: 'OFFER_LETTER' as const, label: 'Signed Offer Letter' }]).map((item) => { const document = selected.documents.find((entry) => entry.document_type === item.type); return <div key={item.type} className="border p-3" style={{ borderColor: 'var(--line-soft)', borderRadius: 'var(--radius-sm)' }}><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-medium" style={{ color: 'var(--ink)' }}>{item.label}</p><p className="mt-1 text-xs" style={{ color: document ? 'var(--status-present)' : 'var(--text-secondary)' }}>{document ? `Uploaded: ${document.file_name}` : 'Required document'}</p></div><div className="flex gap-2">{document && <button type="button" onClick={() => { void view(document); }} className="border px-2 py-1 text-xs" style={{ borderColor: 'var(--line)', borderRadius: 'var(--radius-sm)' }}>View</button>}<label className="cursor-pointer border px-2 py-1 text-xs" style={{ borderColor: 'var(--line)', borderRadius: 'var(--radius-sm)' }}>{document ? 'Replace' : 'Upload'}<input type="file" accept="application/pdf,image/jpeg,image/png" className="hidden" onChange={(event) => { void handleUpload(item.type, event.target.files?.[0]); event.currentTarget.value = ''; }} /></label></div></div></div>; })}</div>}
        </div>}</div>}</Drawer>

        <Drawer open={Boolean(joinerCandidateId)} title="Start onboarding" onClose={() => setJoinerCandidateId('')}><form onSubmit={createJoiner} className="space-y-4"><Field label="New joiner"><select required value={joinerCandidateId} onChange={(event) => setJoinerCandidateId(event.target.value)} className="w-full border px-3 py-2 text-sm" style={inputStyle}><option value="">Select candidate</option>{candidatesWithoutOnboarding.map((candidate: Candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name} · {candidate.email}</option>)}</select></Field><Field label="Joining date"><input required type="date" value={joiningDate} onChange={(event) => setJoiningDate(event.target.value)} className="w-full border px-3 py-2 text-sm" style={inputStyle} /></Field><button disabled={actionLoading} className="w-full py-2.5 text-sm font-medium disabled:opacity-60" style={{ background: 'var(--ink)', color: '#fff', borderRadius: 'var(--radius-sm)' }}>Start onboarding</button></form></Drawer>
    </div>;
}
